<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260517103903 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'renommage de la table post en listing et mise à jour des relations avec les autres entités';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE listing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, localisation_details VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CB0048D412469DE2 ON listing (category_id)');
        $this->addSql('CREATE INDEX IDX_CB0048D48BAC62AF ON listing (city_id)');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D48BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT fk_c53d045f4b89032c');
        $this->addSql('DROP INDEX idx_c53d045f4b89032c');
        $this->addSql('ALTER TABLE image RENAME COLUMN post_id TO listing_id');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045FD4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C53D045FD4619D1A ON image (listing_id)');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT fk_5a8a6c8d12469de2');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT fk_5a8a6c8d8bac62af');
        $this->addSql('DROP TABLE post');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, localisation_details VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, status VARCHAR(50) NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_5a8a6c8d8bac62af ON post (city_id)');
        $this->addSql('CREATE INDEX idx_5a8a6c8d12469de2 ON post (category_id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT fk_5a8a6c8d12469de2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT fk_5a8a6c8d8bac62af FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045FD4619D1A');
        $this->addSql('DROP INDEX IDX_C53D045FD4619D1A');
        $this->addSql('ALTER TABLE image RENAME COLUMN listing_id TO post_id');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT fk_c53d045f4b89032c FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_c53d045f4b89032c ON image (post_id)');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D412469DE2');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D48BAC62AF');
        $this->addSql('DROP TABLE listing');
    }
}
