<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260517145921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78672EEA12469DE2 ON attribute_option (category_id)');
        //$this->addSql('CREATE TABLE category_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, type VARCHAR(100) NOT NULL, is_required BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE listing_attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT FK_78672EEA12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute_option DROP CONSTRAINT FK_78672EEA12469DE2');
        $this->addSql('DROP TABLE attribute_option');
        //$this->addSql('DROP TABLE category_attribute');
        $this->addSql('DROP TABLE listing_attribute_value');
    }
}
